#!/usr/bin/env bash
#
# configure-broker.sh — runs ON a broker VM as root, on EVERY boot, after
# bootstrap-node.sh (kafka-showcase-setup.service oneshot). No-op on the driver.
#
# Reads /etc/kafka-showcase/node.env (written by cloud-init from Terraform):
#   ROLE=broker, NODE_ID, CLUSTER_ID, INTERNAL_IP, EXTERNAL_IP, VOTERS, MOUNT_NVME
#
# Does:
#   1. renders /opt/kafka/config/server.properties for KRaft combined mode
#      (process.roles=broker,controller) with three listeners:
#        INTERNAL   0.0.0.0:9092  advertised as INTERNAL_IP:9092  (VPC, Kubernetes pods)
#        CONTROLLER 0.0.0.0:9093  KRaft quorum
#        EXTERNAL   0.0.0.0:9094  advertised as EXTERNAL_IP:9094  (operator laptop)
#   2. formats the log directory with CLUSTER_ID ONLY when meta.properties is absent;
#      if it exists with a DIFFERENT cluster.id this script exits 1 and leaves the data
#      alone (a replacement broker must not form a second cluster)
#   3. installs/enables kafka.service (Restart=on-failure) and (re)starts it
#
# Log directory: /mnt/kafka-data/data — a subdirectory of the NVMe mount, because an
# ext4 root carries lost+found, which Kafka rejects as a topic directory.
set -euo pipefail

NODE_ENV=/etc/kafka-showcase/node.env
KAFKA_HOME=/opt/kafka
DATA_DIR=/mnt/kafka-data
LOG_DIRS="$DATA_DIR/data"
META="$LOG_DIRS/meta.properties"
PROPS="$KAFKA_HOME/config/server.properties"
INT_PORT=9092; CTL_PORT=9093; EXT_PORT=9094

log() { printf '[configure-broker] %s\n' "$*"; }
fail() { printf '[configure-broker] FAIL: %s\n' "$*" >&2; exit 1; }

[ "$(id -u)" = 0 ] || fail "must run as root"
[ -f "$NODE_ENV" ] || fail "$NODE_ENV not found (cloud-init did not write it)"
# shellcheck disable=SC1090
source "$NODE_ENV"

if [ "${ROLE:-}" != "broker" ]; then
  log "ROLE=${ROLE:-unset}: not a broker, nothing to configure"
  exit 0
fi
: "${NODE_ID:?NODE_ID missing in $NODE_ENV}"
: "${CLUSTER_ID:?CLUSTER_ID missing in $NODE_ENV}"
: "${INTERNAL_IP:?INTERNAL_IP missing in $NODE_ENV}"
: "${EXTERNAL_IP:?EXTERNAL_IP missing in $NODE_ENV}"
: "${VOTERS:?VOTERS missing in $NODE_ENV}"
[[ "$NODE_ID" =~ ^[0-9]+$ ]] || fail "NODE_ID must be numeric, got '$NODE_ID'"
[ -x "$KAFKA_HOME/bin/kafka-server-start.sh" ] || fail "$KAFKA_HOME not installed — bootstrap-node.sh did not run"
if [ "${MOUNT_NVME:-1}" = 1 ]; then
  mountpoint -q "$DATA_DIR" || fail "$DATA_DIR is not a mount point — bootstrap-node.sh did not mount the NVMe device"
fi
mkdir -p "$LOG_DIRS" && chown kafka:kafka "$LOG_DIRS"

# ---------------------------------------------------------------- 1. server.properties
cat > "$PROPS" <<PROPS
# Generated by configure-broker.sh — Apache Kafka KRaft, combined broker+controller.
# Edits are overwritten on every boot; change the generator, not this file.
process.roles=broker,controller
node.id=$NODE_ID
controller.quorum.voters=$VOTERS

listeners=INTERNAL://0.0.0.0:$INT_PORT,CONTROLLER://0.0.0.0:$CTL_PORT,EXTERNAL://0.0.0.0:$EXT_PORT
advertised.listeners=INTERNAL://$INTERNAL_IP:$INT_PORT,EXTERNAL://$EXTERNAL_IP:$EXT_PORT
listener.security.protocol.map=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
inter.broker.listener.name=INTERNAL
controller.listener.names=CONTROLLER

log.dirs=$LOG_DIRS
num.partitions=6
default.replication.factor=3
min.insync.replicas=2
offsets.topic.replication.factor=3
transaction.state.log.replication.factor=3
transaction.state.log.min.isr=2
share.coordinator.state.topic.replication.factor=3
share.coordinator.state.topic.min.isr=2

num.network.threads=8
num.io.threads=8
socket.send.buffer.bytes=1048576
socket.receive.buffer.bytes=1048576
socket.request.max.bytes=104857600
log.retention.hours=168
log.segment.bytes=1073741824
group.initial.rebalance.delay.ms=0
PROPS
chown kafka:kafka "$PROPS"
log "rendered $PROPS (node.id=$NODE_ID, voters=$VOTERS)"

# ---------------------------------------------------------------- 2. storage format
if [ ! -f "$META" ]; then
  log "formatting $LOG_DIRS with cluster id $CLUSTER_ID"
  sudo -u kafka "$KAFKA_HOME/bin/kafka-storage.sh" format -t "$CLUSTER_ID" -c "$PROPS" >/dev/null
else
  HAVE="$(grep -E '^cluster.id=' "$META" | cut -d= -f2 | tr -d '\r')"
  if [ "$HAVE" != "$CLUSTER_ID" ]; then
    fail "$META already holds cluster.id=$HAVE but node.env says CLUSTER_ID=$CLUSTER_ID.
  This broker was formatted for a different cluster. Refusing to start it into this one.
  Either restore the original CLUSTER_ID in Terraform, or wipe $LOG_DIRS on this node
  (its data is lost; re-seed afterwards) and re-run this script."
  fi
  log "already formatted (cluster id $HAVE)"
fi

# ---------------------------------------------------------------- 3. systemd unit
cat > /etc/systemd/system/kafka.service <<UNIT
[Unit]
Description=Apache Kafka (KRaft) — kafka-migration showcase broker $NODE_ID
After=network-online.target
Wants=network-online.target
# Deliberately NOT ordered After=kafka-showcase-setup.service: this script runs INSIDE
# that oneshot and calls 'systemctl restart kafka', which blocks until the kafka start
# job may run; an After= on the still-activating setup unit would deadlock the boot.
# Instead kafka only starts on its own once a formatted log dir exists; the setup
# service restarts it after re-rendering the configuration.
ConditionPathExists=$META

[Service]
User=kafka
Group=kafka
Environment=KAFKA_HEAP_OPTS=-Xms6g -Xmx6g
Environment=LOG_DIR=/var/log/kafka
ExecStart=$KAFKA_HOME/bin/kafka-server-start.sh $PROPS
ExecStop=$KAFKA_HOME/bin/kafka-server-stop.sh
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576
TimeoutStopSec=60

[Install]
WantedBy=multi-user.target
UNIT
systemctl daemon-reload
systemctl enable kafka >/dev/null 2>&1
systemctl restart kafka

for _ in $(seq 1 45); do
  if ss -ltn | grep -q ":$INT_PORT "; then
    log "kafka listening on $INT_PORT/$CTL_PORT/$EXT_PORT (node $NODE_ID)"
    exit 0
  fi
  if ! systemctl is-active --quiet kafka; then
    journalctl -u kafka --no-pager -n 40 >&2
    tail -n 40 /var/log/kafka/server.log >&2 2>/dev/null || true
    fail "kafka unit died"
  fi
  sleep 2
done
tail -n 40 /var/log/kafka/server.log >&2 2>/dev/null || true
fail "kafka did not open port $INT_PORT within 90s"
